# Generated by Django 3.2.19 on 2023-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),  # noqa E501
        ),
    ]
