# Generated by Django 3.2.19 on 2023-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Tips', 'Tips'), ('Guides', 'Guides')], default='Cars', max_length=25),  # noqa E501
        ),
    ]
