# Generated by Django 3.2.19 on 2023-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
