# Generated by Django 3.2.19 on 2023-07-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230718_1151'),
        ('checkout', '0006_remove_orderlineitem_product_size'),
        ('reviews', '0004_remove_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.order', unique=True),  # noqa E501
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='products.product'),  # noqa E501
            preserve_default=False,
        ),
    ]
