# Generated by Django 3.2.19 on 2023-07-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_orderlineitem_product_size'),
        ('reviews', '0005_auto_20230729_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='checkout.order'),  # noqa E501
        ),
    ]
