# Generated by Django 3.2.19 on 2023-07-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230718_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
