# Generated by Django 3.2.19 on 2023-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='garage_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='history_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='premium_check',
            field=models.BooleanField(default=False),
        ),
    ]
